### ISSUE TITLE
Fail to load ckpt file

### ISSUE THREAD

**Issue by oenewbee** [ruc-aimc-lab/nT2VR#2]
Hi, very appreciate for your excellent work about negation understanding!

But I met some problems when loading your CLIP-bnl ckpt (predictor.py, line 423), which shows the traceback:
- - --------------------------------------------------------
Traceback (most recent call last):
  File "predictor.py", line 505, in <module>
    main()
  File "predictor.py", line 423, in main
    checkpoint = torch.load(resume_file, map_location='cpu')
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'txt2vec'
- - --------------------------------------------------------
Similar to the issue https://github.com/pytorch/pytorch/issues/18325, it seems that the module 'txt2vec' is missing in the project file. Are there any solutions to this problem? Hope for your reply~

**Comment by sherlockeded** [comment]
> Hi, very appreciate for your excellent work about negation understanding!
> 
> But I met some problems when loading your CLIP-bnl ckpt (predictor.py, line 423), which shows the traceback:
> 
> Traceback (most recent call last): File "predictor.py", line 505, in main() File "predictor.py", line 423, in main checkpoint = torch.load(resume_file, map_location='cpu') File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 592, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 851, in _load result = unpickler.load() ModuleNotFoundError: No module named 'txt2vec'
> 
> Similar to the issue [pytorch/pytorch#18325](https://github.com/pytorch/pytorch/issues/18325), it seems that the module 'txt2vec' is missing in the project file. Are there any solutions to this problem? Hope for your reply~

Thank you for your intereset. I make a new push, it should fix this problem.

**Comment by oenewbee** [comment]
> > Hi, very appreciate for your excellent work about negation understanding!
> > But I met some problems when loading your CLIP-bnl ckpt (predictor.py, line 423), which shows the traceback:
> > Traceback (most recent call last): File "predictor.py", line 505, in main() File "predictor.py", line 423, in main checkpoint = torch.load(resume_file, map_location='cpu') File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 592, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 851, in _load result = unpickler.load() ModuleNotFoundError: No module named 'txt2vec'
> > Similar to the issue [pytorch/pytorch#18325](https://github.com/pytorch/pytorch/issues/18325), it seems that the module 'txt2vec' is missing in the project file. Are there any solutions to this problem? Hope for your reply~
> 
> Thank you for your intereset. I make a new push, it should fix this problem.

Thanks~ The bug has been fixed!
